### ISSUE TITLE
practice 12 is unclear

### ISSUE THREAD

**Issue by mlc** [meetup/engineering-home#2]
There is some tension between the practice's advice to "own and operate our own systems" and the unstated but oft-heard idea of outsourcing whenever possible. I suggest either rewording the principle to clarify what is meant, or rethinking it to be more in line with our actual current practices.

**Comment by yvettepasqua** [comment]
It's definitely the former -- engineers who write code owning and operating it and the systems it runs in production versus a separate ops or devops team doing it. We don't actually outsource any operations right now, so I'm not sure what you're referring to? Did you click on the links and read them? Does it still not make sense after reading the links? Would love to know if that's the case.

**Comment by yvettepasqua** [comment]
> There is some tension between the practice's advice to "own and operate our own systems" and the unstated but oft-heard idea of outsourcing whenever possible. I suggest either rewording the principle to clarify what is meant, or rethinking it to be more in line with our actual current practices.

It's definitely the former -- engineers who write code owning and operating it and the systems it runs in production versus a separate ops or devops team doing it. We don't actually outsource any operations right now, so I'm not sure what you're referring to? Did you click on the links and read them? Does it still not make sense after reading the links? Would love to know if that's the case.

**Comment by mlc** [comment]
> We don't actually outsource any operations right now

I think this gets to precisely the heart of my confusion: we spend a lot of money with AWS because we think they are better at operating servers than we are, with Braze because we think they are better at operating email than we we are, with the new chat service vendor, and so on. If I read between the lines of the practice as stated, I can maybe come to the understanding that these are not "operations" in the sense that you seem to mean here, but I still disagree that it is clear or obvious as written.

> Engineers who write code owning and operating it and the systems it runs in production versus a separate ops or devops team doing it

This is, in my view, a much clearer way of saying the important thing here.

**Comment by yvettepasqua** [comment]
Thanks for clarifying Mike, and I see what you mean. Do you think it's clearer to say something like we "Own and operate the software we write in production" or something similar? I'll think about the best way to re-phrase it.

**Comment by mlc** [comment]
Yes, I think that's much clearer. Thanks!

**Comment by yvettepasqua** [comment]
Ok, I updated it! If I think of an even better set of words (or if you do) I'll update again!
