### ISSUE TITLE
on lasting engineering solutions

### ISSUE THREAD

**Issue by softprops** [meetup/engineering-home#3]
I want to call out the `lasting engineering solutions` part of practices as a dual-edged sword and maybe something we may want to reword or remove. The sentiment is positive, the historical interpretation can be negative.

While fitting engineering solutions are always goal, the "lasting" property solution historically has often created contention with our capacity to adapt and evolve to new needs as the solutions that were designed to meet previous needs endure and continue to co-exist with new solutions, which themselves often have the habit of becoming the "new old, yet everlasting solution".

A good argument could be made that those solutions didn't "last" in the sense that organizational needs changed and the solution no longer fits but those solutions often "last" in terms of not going away in practice.  To disambiguate interpretations between these, it may be a good idea to reword this for the purpose of clarifying what we aim for and what we try to avoid.

I believe lasting engineering solutions can be viewed as a positive aspiration goal, but as the practice doc puts emphasis on "build for change", lasting solutions seem in direct conflict. I would hesitate to suggest substituting a word that implies disposability but in a sense I believe disposability is a key ingredient to changeability.

**Comment by yvettepasqua** [comment]
This is great feedback, Doug! I think we're on the same page with the sentiment, as you're calling out that "lasting" may lead people down a road of thinking we literally mean "should stay in the code forever just as they are" vs what I'm trying to communicate which is "should easily evolve as our product changes." I'll mull over a word choice change, but if you have any suggestions, I'd love to hear them!

**Comment by yvettepasqua** [comment]
> This is great feedback, Doug! I think we're on the same page with the sentiment, as you're calling out that "lasting" may lead people down a road of thinking we literally mean "should stay in the code forever just as they are" vs what I'm trying to communicate which is "should easily evolve as our product changes." I'll mull over a word choice change, but if you have any suggestions, I'd love to hear them!

thanks again for this feedback @softprops! i've thought about it and decided to remove the line all together with the consultation of Gruber too. the line wasn't adding enough value to be at the top and the main value i saw was calling out that we are here to bring value to our customers but that's in principle #1 anyway. so less is more!
